version: "3.8"

services:
  cog-tile-server:
    build:
      context: .
      dockerfile: Dockerfile.improved
    image: cog-tile-server:latest
    container_name: cog-tile-server
    
    # Fixed port mapping - use 8001 consistently
    ports:
      - "8084:8001"
    
    # Persistent volumes for cache and data
    volumes:
      - cog_cache:/app/cache
      - /mnt/data/ocean_portal/datasets:/app/datasets:ro
    
    # Optimized environment variables
    environment:
      # GDAL Optimization
      GDAL_CACHEMAX: "1024"
      GDAL_NUM_THREADS: "ALL_CPUS"
      GDAL_TIFF_OVR_BLOCKSIZE: "256"
      GDAL_DISABLE_READDIR_ON_OPEN: "EMPTY_DIR"
      VSI_CACHE: "TRUE"
      VSI_CACHE_SIZE: "25000000"
      
      # Application settings
      PYTHONUNBUFFERED: "1"
      CACHE_DIR: "/app/cache"
      LOG_LEVEL: "INFO"
      
      # Performance tuning
      GDAL_HTTP_TIMEOUT: "30"
      GDAL_HTTP_MAX_RETRY: "3"
      CPL_VSIL_CURL_CACHE_SIZE: "200000000"
    
    # Resource limits to prevent OOM
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    # Restart policy
    restart: unless-stopped
    
    # Fixed health check with correct endpoint and port
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Network configuration
    networks:
      - cog-network

# Named volumes for persistence
volumes:
  cog_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/cog_tiler/cache

# Dedicated network
networks:
  cog-network:
    driver: bridge